baseURL = "/"

DefaultContentLanguage = "en"
languageCode = "en-us"
summaryLength = 50
buildFuture = true
enableRobotsTXT = true
theme = "evictionlab"

[markup.goldmark.renderer]
unsafe= true

[Languages]
[Languages.en]
weight = 0
title = "Eviction Lab"
languageName = "English"

[[Languages.en.menu.main]]
    name = "Home"
    weight = 1
    url = "/"
[[Languages.en.menu.main]]
    name = "Map & Data"
    weight = 2
    url = "/map/"
[[Languages.en.menu.main]]
    name = "Eviction Rankings"
    weight = 3
    url = "/rankings/"
[[Languages.en.menu.main]]
    name = "Eviction Tracking System"
    weight = 5
    url = "/eviction-tracking/"      
[[Languages.en.menu.main]]
    name = "Policy Scorecard"
    weight = 6
    url = "/covid-policy-scorecard/"    
[[Languages.en.menu.main]]
    name = "About Us"
    weight = 7
    url = "/about/"
[[Languages.en.menu.main]]
    name = "Why Eviction Matters"
    weight = 8
    url = "/why-eviction-matters"
[[Languages.en.menu.main]]
    name = "Methods"
    weight = 9
    url = "/methods/"
[[Languages.en.menu.main]]
    name = "Help & FAQ"
    weight = 10
    url = "/help-faq/"
[[Languages.en.menu.main]]
    name = "Updates"
    weight = 11
    url = "/updates/"
[[Languages.en.menu.main]]
    name = " Blog"
    weight = 12
    url = "/updates/blog"
[[Languages.en.menu.main]]
    name = " Research"
    weight = 13
    url = "/updates/research"
[[Languages.en.menu.main]]
    name = " Reporting"
    weight = 14
    url = "/updates/reporting"            

[[Languages.en.menu.footer]]
    name = "Home"
    weight = 1
    url = "/"
[[Languages.en.menu.footer]]
    name = "Map & Data"
    weight = 2
    url = "/map/"
[[Languages.en.menu.footer]]
    name = "Eviction Rankings"
    weight = 3
    url = "/rankings/"
[[Languages.en.menu.footer]]
    name = "COVID-19 Policy Scorecard"
    weight = 4
    url = "/covid-policy-scorecard/" 
[[Languages.en.menu.footer]]
    name = "Eviction Tracking System"
    weight = 6
    url = "/eviction-tracking/"        
[[Languages.en.menu.footer]]
    name = "About Us"
    weight = 7
    url = "/about/"
[[Languages.en.menu.footer]]
    name = "Why Eviction Matters"
    weight = 8
    url = "/why-eviction-matters"
[[Languages.en.menu.footer]]
    name = "Methods"
    weight = 9
    url = "/methods/"
[[Languages.en.menu.footer]]
    name = "Help & FAQ"
    weight = 10
    url = "/help-faq/"
[[Languages.en.menu.footer]]
    name = "Updates"
    weight = 11
    url = "/updates/"
[[Languages.en.menu.footer]]
    name = "Contact Us"
    weight = 11
    url = "/contact"
[[Languages.en.menu.footer]]
    name = "Get the Data"
    weight = 12
    url = "/get-the-data"
[[Languages.en.menu.footer]]
    name = "Data Request Application"
    weight = 13
    url = "/data-request"
[[Languages.en.menu.footer]]
    name = "Media Guide"
    weight = 14
    url = "/media-guide/"    


[[Languages.en.menu.updates]]
    name = "Events"
    weight = -80
    identifier = "about"
    url = "/updates/events/"
[[Languages.en.menu.updates]]
    name = "Research"
    weight = -110
    url = "/updates/research/"
[[Languages.en.menu.updates]]
    name = "EL Research"
    parent = "Research"
    weight = -94
    url = "/updates/research/el-research" 
[[Languages.en.menu.updates]]
    name = "Outside Research"
    parent = "Research"
    weight = -96
    url = "/updates/research/outside-research"        
[[Languages.en.menu.updates]]
    name = "Reporting"
    weight = -90
    url = "/updates/reporting/"
[[Languages.en.menu.updates]]
    name = "Blog"
    weight = -100
    url = "/updates/blog/"


[Languages.es]
weight = 1
title = "Eviction Lab"
languageName = "Español"


[[Languages.es.menu.main]]
    name = "Inicio"
    weight = 1
    url = "/es/"
[[Languages.es.menu.main]]
    name = "Mapa y datos"
    weight = 2
    url = "/map/#/2016%3Flang%3Des"
[[Languages.es.menu.main]]
    name = "Rankings de desalojos"
    weight = 3
    url = "/rankings/#/evictions%3Flang%3Des"
[[Languages.es.menu.main]]
    name = "Eviction Tracking System"
    weight = 5
    url = "/eviction-tracking/"      
[[Languages.es.menu.main]]
    name = "Policy Scorecard"
    weight = 6
    url = "/covid-policy-scorecard/"      
[[Languages.es.menu.main]]
    name = "Acerca de nosotros"
    weight = 7
    url = "/es/about/"
[[Languages.es.menu.main]]
    name = "Por qué es importante el desalojo"
    weight = 8
    url = "/es/why-eviction-matters"
[[Languages.es.menu.main]]
    name = "Métodos"
    weight = 9
    url = "/es/methods/"
[[Languages.es.menu.main]]
    name = "Ayuda y preguntas frequentes"
    weight = 10
    url = "/es/help-faq/"
[[Languages.es.menu.main]]
    name = "Actualizaciones"
    weight = 11
    url = "/updates/"
[[Languages.es.menu.main]]
    name = "• Blog"
    weight = 12
    url = "/updates/blog"
[[Languages.es.menu.main]]
    name = "• Research"
    weight = 13
    url = "/updates/research"
[[Languages.es.menu.main]]
    name = "• Reporting"
    weight = 14    
    url = "/updates/reporting"

[[Languages.es.menu.footer]]
    name = "Inicio"
    weight = 1
    url = "/es/"
[[Languages.es.menu.footer]]
    name = "Mapa y datos"
    weight = 2
    url = "/map/#/2016%3Flang%3Des"
[[Languages.es.menu.footer]]
    name = "Rankings de desalojos"
    weight = 3
    url = "/rankings/#/evictions%3Flang%3Des"
[[Languages.es.menu.footer]]
    name = "Acerca de nosotros"
    weight = 4
    url = "/es/about/"
[[Languages.es.menu.footer]]
    name = "Por qué es importante el desalojo"
    weight = 5
    url = "/es/why-eviction-matters"
[[Languages.es.menu.footer]]
    name = "COVID-19 Policy Scorecard"
    weight = 6
    url = "/covid-policy-scorecard/" 
[[Languages.es.menu.footer]]
    name = "Eviction Tracking System"
    weight = 7
    url = "/eviction-tracking/"       
[[Languages.es.menu.footer]]
    name = "Métodos"
    weight = 8
    url = "/es/methods/"
[[Languages.es.menu.footer]]
    name = "Ayuda y preguntas frequentes"
    weight = 9
    url = "/es/help-faq/"
[[Languages.es.menu.footer]]
    name = "Actualizaciones"
    weight = 10
    url = "/updates/"
[[Languages.es.menu.footer]]
    name = "Contactarnos"
    weight = 11
    url = "/es/contact"
[[Languages.es.menu.footer]]
    name = "Obtener los datos"
    weight = 11
    url = "/es/get-the-data"
[[Languages.es.menu.footer]]
    name = "Aplicación de solicitud de datos"
    weight = 12
    url = "/es/data-request"
[[Languages.es.menu.footer]]
    name = "Guía de medios"
    weight = 13
    url = "/media-guide/"     


[[Languages.es.menu.updates]]
    name = "Events"
    weight = -80
    identifier = "about"
    url = "/updates/events/"
[[Languages.es.menu.updates]]
    name = "Research"
    weight = -110
    url = "/updates/research/"
[[Languages.es.menu.updates]]
    name = "EL Research"
    parent = "Research"
    weight = -94
    url = "/updates/research/el-research" 
[[Languages.es.menu.updates]]
    name = "Outside Research"
    parent = "Research"
    weight = -96
    url = "/updates/research/outside-research"        
[[Languages.es.menu.updates]]
    name = "Media"
    weight = -90
    url = "/updates/media/"
[[Languages.es.menu.updates]]
    name = "Blog"
    weight = -100
    url = "/updates/blog/"
