baseURL = "/"

DefaultContentLanguage = "en"
languageCode = "en-us"
summaryLength = 50
buildFuture = true
enableRobotsTXT = true
theme = "evictionlab"

[markup.goldmark.renderer]
unsafe= true

[Languages]
[Languages.en]
weight = 0
title = "Eviction Lab"
languageName = "English"

[[Languages.en.menu.main]]
    name = "Home"
    weight = 1
    url = "/"
[[Languages.en.menu.main]]
    name = "Latest Data"
    weight = 2
[[Languages.en.menu.main]]
    name = "Eviction Tracking System"
    weight = 3
    url = "/eviction-tracking/" 
[[Languages.en.menu.main]]
    name = "Findings & Stories"
    weight = 6
[[Languages.en.menu.main]]
    name = "Eviction Lab Research"
    weight = 7
    url = "/research/"    
[[Languages.en.menu.main]]
    name = "Articles & Updates"
    weight = 8
    url = "/updates/"
[[Languages.en.menu.main]]
    name = "National Zoning & Land Use Database"
    weight = 9
    url = "/national-zoning-and-land-use-database/"
[[Languages.en.menu.main]]
    name = "National Data (2000-2018)"
    weight = 11
[[Languages.en.menu.main]]
    name = "National Eviction Map"
    weight = 12
    url = "/map/"
[[Languages.en.menu.main]]
    name = "Eviction Rankings"
    weight = 13
    url = "/rankings/"
[[Languages.en.menu.main]]
    name = "About the Lab"
    weight = 14
[[Languages.en.menu.main]]
    name = "Mission & Team"
    weight = 15
    url = "/about/"
[[Languages.en.menu.main]]
    name = "Why Eviction Matters"
    weight = 16
    url = "/why-eviction-matters"
[[Languages.en.menu.main]]
    name = "Methods"
    weight = 17
    url = "/methods/"
[[Languages.en.menu.main]]
    name = "FAQ"
    weight = 18
    url = "/help-faq/"


[[Languages.en.menu.footer]]
    name = "Home"
    weight = 1
    url = "/"  
[[Languages.en.menu.footer]]
    name = "National Eviction Map"
    weight = 2
    url = "/map/"
[[Languages.en.menu.footer]]
    name = "Eviction Tracking System"
    weight = 3
    url = "/eviction-tracking/"  
[[Languages.en.menu.footer]]
    name = "Research"
    weight = 4
    url = "/research/"        
[[Languages.en.menu.footer]]
    name = "Eviction Rankings"
    weight = 5
    url = "/rankings/"
[[Languages.en.menu.footer]]
    name = "National Zoning & Land Use Database"
    weight = 6
    url = "/national-zoning-and-land-use-database/"
[[Languages.en.menu.footer]]
    name = "About Us"
    weight = 7
    url = "/about/"
[[Languages.en.menu.footer]]
    name = "Why Eviction Matters"
    weight = 8
    url = "/why-eviction-matters"
[[Languages.en.menu.footer]]
    name = "Methods"
    weight = 9
    url = "/methods/"
[[Languages.en.menu.footer]]
    name = "Help & FAQ"
    weight = 10
    url = "/help-faq/"
[[Languages.en.menu.footer]]
    name = "Updates"
    weight = 11
    url = "/updates/"
[[Languages.en.menu.footer]]
    name = "Get the Data"
    weight = 12
    url = "/get-the-data"
[[Languages.en.menu.footer]]
    name = "Data Request Application"
    weight = 13
    url = "/data-request"
[[Languages.en.menu.footer]]
    name = "Media Guide"
    weight = 14
    url = "/media-guide/"
[[Languages.en.menu.footer]]
    name = "Contact Us"
    weight = 15
    url = "/contact"    


[[Languages.en.menu.updates]]
    name = "Events"
    weight = -80
    identifier = "about"
    url = "/updates/events/"
[[Languages.en.menu.updates]]
    name = "Research"
    weight = -110
    url = "/updates/research/"
[[Languages.en.menu.updates]]
    name = "EL Research"
    parent = "Research"
    weight = -94
    url = "/updates/research/el-research"
[[Languages.en.menu.updates]]
    name = "Outside Research"
    parent = "Research"
    weight = -96
    url = "/updates/research/outside-research"
[[Languages.en.menu.updates]]
    name = "Reporting"
    weight = -90
    url = "/updates/reporting/"
[[Languages.en.menu.updates]]
    name = "Blog"
    weight = -100
    url = "/updates/blog/"


[Languages.es]
weight = 1
title = "Eviction Lab"
languageName = "Español"


[[Languages.es.menu.main]]
    name = "Inicio"
    weight = 1
    url = "/es/"
[[Languages.es.menu.main]]
    name = "Últimos datos"
    weight = 2
[[Languages.es.menu.main]]
    name = "Eviction Tracking System"
    weight = 3
    url = "/eviction-tracking/"
[[Languages.es.menu.main]]
    name = "Hallazgos e historias más recientes"
    weight = 6
[[Languages.es.menu.main]]
    name = "Eviction Lab Research"
    weight = 7
    url = "/research/"
[[Languages.es.menu.main]]
    name = "Articles & Updates"
    weight = 7
    url = "/updates/"  
[[Languages.es.menu.main]]
    name = "National Zoning & Land Use Database"
    weight = 8
    url = "/national-zoning-and-land-use-database/"         
[[Languages.es.menu.main]]
    name = "Datos nacionales (2000-2018)"
    weight = 11
[[Languages.es.menu.main]]
    name = "National Eviction Map"
    weight = 12
    url = "/map/#/2016%3Flang%3Des"
[[Languages.es.menu.main]]
    name = "Rankings de desalojos"
    weight = 13
    url = "/rankings/#/evictions%3Flang%3Des"
[[Languages.es.menu.main]]
    name = "Sobre el laboratorio"
    weight = 14
[[Languages.es.menu.main]]
    name = "Misión y equipo"
    weight = 15
    url = "/es/about/"
[[Languages.es.menu.main]]
    name = "Por qué es importante el desalojo"
    weight = 16
    url = "/es/why-eviction-matters"
[[Languages.es.menu.main]]
    name = "Métodos"
    weight = 17
    url = "/es/methods/"
[[Languages.es.menu.main]]
    name = "Preguntas frequentes"
    weight = 18
    url = "/es/help-faq/"

[[Languages.es.menu.footer]]
    name = "Inicio"
    weight = 1
    url = "/es/"
[[Languages.es.menu.footer]]
    name = "Mapa Nacional de Desalojo"
    weight = 2
    url = "/map/#/2016%3Flang%3Des"
[[Languages.es.menu.footer]]
    name = "Eviction Tracking System"
    weight = 3
    url = "/eviction-tracking/"
[[Languages.es.menu.footer]]
    name = "Research"
    weight = 4
    url = "/research/"        
[[Languages.es.menu.footer]]
    name = "Rankings de desalojos"
    weight = 5
    url = "/rankings/#/evictions%3Flang%3Des"
[[Languages.es.menu.footer]]
    name = "National Zoning & Land Use Database"
    weight = 6
    url = "/national-zoning-and-land-use-database/"    
[[Languages.es.menu.footer]]
    name = "Acerca de nosotros"
    weight = 7
    url = "/es/about/"
[[Languages.es.menu.footer]]
    name = "Por qué es importante el desalojo"
    weight = 8
    url = "/es/why-eviction-matters"
[[Languages.es.menu.footer]]
    name = "Métodos"
    weight = 9
    url = "/es/methods/"
[[Languages.es.menu.footer]]
    name = "Ayuda y preguntas frequentes"
    weight = 10
    url = "/es/help-faq/"
[[Languages.es.menu.footer]]
    name = "Actualizaciones"
    weight = 11
    url = "/updates/"
[[Languages.es.menu.footer]]
    name = "Obtener los datos"
    weight = 12
    url = "/es/get-the-data"
[[Languages.es.menu.footer]]
    name = "Aplicación de solicitud de datos"
    weight = 13
    url = "/es/data-request"
[[Languages.es.menu.footer]]
    name = "Guía de medios"
    weight = 14
    url = "/media-guide/"
[[Languages.es.menu.footer]]
    name = "Contactarnos"
    weight = 15
    url = "/es/contact"    


[[Languages.es.menu.updates]]
    name = "Events"
    weight = -80
    identifier = "about"
    url = "/updates/events/"
[[Languages.es.menu.updates]]
    name = "Research"
    weight = -110
    url = "/updates/research/"
[[Languages.es.menu.updates]]
    name = "EL Research"
    parent = "Research"
    weight = -94
    url = "/updates/research/el-research"
[[Languages.es.menu.updates]]
    name = "Outside Research"
    parent = "Research"
    weight = -96
    url = "/updates/research/outside-research"
[[Languages.es.menu.updates]]
    name = "Media"
    weight = -90
    url = "/updates/media/"
[[Languages.es.menu.updates]]
    name = "Blog"
    weight = -100
    url = "/updates/blog/"
