backend:
 name: github
 repo: EvictionLab/eviction-lab-website
 branch: staging
 
# FOR LOCAL DEVELOPMENT:
# ---
# - uncomment the backend below
# - run `npx netlify-cms-proxy-server` to serve content

# backend:
#   name: proxy
#   proxy_url: http://localhost:8081/api/v1
#   branch: end-of-moratorium-faq # optional, defaults to master

media_folder: "static/uploads" # Folder where user uploaded files should go
# publish_mode: editorial_workflow
public_folder: "/uploads" # The src attribute for uploaded media will begin with /uploads

collections:
  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    preview_path: /eviction-tracking/{{slug}}
    files:
      - label: "Eviction Tracking"
        name: "tracker"
        file: "content/eviction-tracking/_index.md"
        identifier_field: name
        fields:
          - {
              label: "Draft",
              name: "draft",
              widget: "boolean",
              hint: "When draft is on, the page will not be published to the live site",
            }
          - label: "Meta"
            name: "cascade"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Browser Window Title",
                  name: title,
                  widget: string,
                  hint: "Title for the browser window or tab",
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "string",
                  hint: "Not visible, but used for search engine optimization",
                }
              - {
                  label: "Social Description",
                  name: "socialDescription",
                  widget: "string",
                  hint: "Description for the thumbnail when page is shared on social media",
                }
              - {
                  label: "Facebook Share Image",
                  name: "fbImage",
                  widget: "image",
                  hint: "Image used when page is shared on Facebook",
                }
              - {
                  label: "Twitter Share Image",
                  name: "twImage",
                  widget: "image",
                  hint: "Image used when page is shared on Twitter",
                }
          - { label: Heading, name: h1, widget: string }
          - { label: "Updated Date", name: "date", widget: "date" }
          - { label: "Intro", name: "intro", widget: "markdown" }
          - { label: "Eviction Crisis", name: "crisis", widget: "markdown" }
          - { label: "Additional Info", name: "additional", widget: "markdown" }
          - { label: "Where's my city?", name: "where", widget: "markdown" }
      - label: "Eviction Tracking (Methods)"
        name: "methods"
        file: "content/eviction-tracking/methods.md"
        identifier_field: name
        fields:
          - {
              label: "Draft",
              name: "draft",
              widget: "boolean",
              hint: "When draft is on, the page will not be published to the live site",
            }
          - label: "Meta"
            name: "cascade"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Browser Window Title",
                  name: title,
                  widget: string,
                  hint: "Title for the browser window or tab",
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "string",
                  hint: "Not visible, but used for search engine optimization",
                }
              - {
                  label: "Social Description",
                  name: "socialDescription",
                  widget: "string",
                  hint: "Description for the thumbnail when page is shared on social media",
                }
              - {
                  label: "Facebook Share Image",
                  name: "fbImage",
                  widget: "image",
                  hint: "Image used when page is shared on Facebook",
                }
              - {
                  label: "Twitter Share Image",
                  name: "twImage",
                  widget: "image",
                  hint: "Image used when page is shared on Twitter",
                }
          - {
              label: Page Name,
              name: h1,
              widget: string,
              hint: "used in the breadcrumb",
            }
          - { label: "Updated Date", name: "date", widget: "date" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Eviction Tracking (Similar Resources)"
        name: "similar-resources"
        file: "content/eviction-tracking/similar-resources.md"
        identifier_field: name
        fields:
          - {
              label: "Draft",
              name: "draft",
              widget: "boolean",
              hint: "When draft is on, the page will not be published to the live site",
            }
          - label: "Meta"
            name: "cascade"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Browser Window Title",
                  name: title,
                  widget: string,
                  hint: "Title for the browser window or tab",
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "string",
                  hint: "Not visible, but used for search engine optimization",
                }
              - {
                  label: "Social Description",
                  name: "socialDescription",
                  widget: "string",
                  hint: "Description for the thumbnail when page is shared on social media",
                }
              - {
                  label: "Facebook Share Image",
                  name: "fbImage",
                  widget: "image",
                  hint: "Image used when page is shared on Facebook",
                }
              - {
                  label: "Twitter Share Image",
                  name: "twImage",
                  widget: "image",
                  hint: "Image used when page is shared on Twitter",
                }
          - {
              label: Page Name,
              name: h1,
              widget: string,
              hint: "used in the breadcrumb",
            }
          - { label: "Updated Date", name: "date", widget: "date" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Eviction Tracking (Acknowledgements)"
        name: "acknowledgements"
        identifier_field: name
        file: "content/eviction-tracking/acknowledgements.md"
        fields:
          - {
              label: "Draft",
              name: "draft",
              widget: "boolean",
              hint: "When draft is on, the page will not be published to the live site",
            }
          - label: "Meta"
            name: "cascade"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Browser Window Title",
                  name: title,
                  widget: string,
                  hint: "Title for the browser window or tab",
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "string",
                  hint: "Not visible, but used for search engine optimization",
                }
              - {
                  label: "Social Description",
                  name: "socialDescription",
                  widget: "string",
                  hint: "Description for the thumbnail when page is shared on social media",
                }
              - {
                  label: "Facebook Share Image",
                  name: "fbImage",
                  widget: "image",
                  hint: "Image used when page is shared on Facebook",
                }
              - {
                  label: "Twitter Share Image",
                  name: "twImage",
                  widget: "image",
                  hint: "Image used when page is shared on Twitter",
                }
          - {
              label: Page Name,
              name: h1,
              widget: string,
              hint: "used in the breadcrumb",
            }
          - { label: "Updated Date", name: "date", widget: "date" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Similar Resources", name: "similar", widget: "markdown" }
      - label: "Eviction Tracking (Get the Data)"
        name: "get-the-data"
        identifier_field: name
        file: "content/eviction-tracking/get-the-data.md"
        fields:
          - {
              label: "Draft",
              name: "draft",
              widget: "boolean",
              hint: "When draft is on, the page will not be published to the live site",
            }
          - label: "Meta"
            name: "cascade"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Browser Window Title",
                  name: title,
                  widget: string,
                  hint: "Title for the browser window or tab",
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "string",
                  hint: "Not visible, but used for search engine optimization",
                }
              - {
                  label: "Social Description",
                  name: "socialDescription",
                  widget: "string",
                  hint: "Description for the thumbnail when page is shared on social media",
                }
              - {
                  label: "Facebook Share Image",
                  name: "fbImage",
                  widget: "image",
                  hint: "Image used when page is shared on Facebook",
                }
              - {
                  label: "Twitter Share Image",
                  name: "twImage",
                  widget: "image",
                  hint: "Image used when page is shared on Twitter",
                }
          - {
              label: Page Name,
              name: h1,
              widget: string,
              hint: "used in the breadcrumb",
            }
          - { label: "Updated Date", name: "date", widget: "date" }
          - { label: "Introduction", name: intro, widget: markdown }
          - label: "Table Column Headers"
            name: "headers"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Header 1", name: "siteheader", widget: "string" }
              - { label: "Header 2", name: "baselineheader", widget: "string" }
              - { label: "Header 3", name: "geoheader", widget: "string" }
              - { label: "Header 4", name: "fileheader", widget: "string" }
          - label: Data Table Rows
            name: data
            widget: list
            fields:
              - { label: Site, name: site, widget: string }
              - { label: Baseline Years, name: years, widget: string }
              - { label: Smallest Geography, name: geo, widget: string }
              - { label: Data File, name: file, widget: file }
          - { label: "Body (below table)", name: "body", widget: "markdown" }
  - name: "eviction-tracking"
    identifier_field: "h1"
    label: "Eviction Tracking"
    folder: "/content/eviction-tracking"
    extension: md
    create: true
    slug: "{{fields.slug}}"
    filter: { field: "collection", value: true } # only show collection items
    editor:
      preview: false
    preview_path: eviction-tracking/{{slug}}
    fields: # The fields for each document, usually in front matter
      - {
          label: "Collection",
          name: "collection",
          widget: "hidden",
          default: true,
        }
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          hint: "When draft is on, the page will not be published to the live site",
          default: true,
        }
      - {
          label: "Browser Title",
          name: "title",
          widget: "string",
          hint: "Browser window title",
        }
      - { label: "City Name", name: "h1", widget: "string" }
      - {
          label: "Slug (URL)",
          name: "slug",
          widget: "string",
          hint: "Should match city name and 2 letter state code (e.g. el-paso-tx)",
        }
      - { label: "Updated Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "research" # Used in routes, e.g., /admin/collections/blog
    label: "Research posts" # Used in the UI
    folder: "/content/updates/research" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: md
    editor:
      preview: false
    preview_path: "{{fields.url}}"
    fields: # The fields for each document, usually in front matter
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          hint: "When draft is on, the page will not be published to the live site",
        }
      - {
          label: "Child Of",
          name: "childof",
          widget: "hidden",
          default: "research",
        }
      - { label: "URL", name: "url", widget: "string" }
      - {
          label: "Content Type",
          name: "contenttype",
          widget: "hidden",
          default: "updates",
        }
      - {
          label: "Content Category",
          name: "contentcat",
          widget: "hidden",
          default: "blog",
        }
      - {
          label: "Featured on Front Page",
          name: "featured",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Featured In Updates index pages",
          name: "in_index",
          widget: "boolean",
          default: true,
        }
      - { label: "Blog Post Title", name: "title", widget: "string" }
      - { label: "Created Date", name: "date", widget: "datetime" }
      - { label: "Author Name", name: "postauthorname", widget: "string" }
      - { label: "Author Title", name: "postauthortitle", widget: "string" }
      - {
          label: "Author Photo",
          name: "authorpic",
          widget: "image",
          default: "images/uploads/james_hendrickson_thumb.jpg",
          required: false,
        }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          required: false,
        }
      - {
          label: "Social Media / Search Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - {
          label: "Excerpt for Articles List",
          name: "listSummary",
          widget: "string",
          required: false,
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          buttons: ["bold", "italic", "link", "bulleted-list", "numbered-list"],
        }

  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog posts" # Used in the UI
    folder: "/content/updates/blog" # The path to the folder where the documents are stored
    path: '{{slug}}/'
    create: true # Allow users to create new documents in this collection
    extension: md
    editor:
      preview: false
    preview_path: "{{fields.url}}"
    fields: # The fields for each document, usually in front matter
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          hint: "When draft is on, the page will not be published to the live site",
        }
      - {
          label: "Child Of",
          name: "childof",
          widget: "hidden",
          default: "blog",
        }
      - { label: "URL", name: "url", widget: "string" }
      - {
          label: "Content Type",
          name: "contenttype",
          widget: "hidden",
          default: "updates",
        }
      - {
          label: "Content Category",
          name: "contentcat",
          widget: "hidden",
          default: "blog",
        }
      - {
          label: "Featured on Front Page",
          name: "featured",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Featured In Updates index pages",
          name: "in_index",
          widget: "boolean",
          default: true,
        }
      - { label: "Blog Post Title", name: "title", widget: "string" }
      - { label: "Created Date", name: "date", widget: "datetime" }
      - { label: "Author Name", name: "postauthorname", widget: "string" }
      - { label: "Author Title", name: "postauthortitle", widget: "string" }
      - {
          label: "Author Photo",
          name: "authorpic",
          widget: "image",
          default: "images/uploads/james_hendrickson_thumb.jpg",
          required: false,
        }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          required: false,
        }
      - {
          label: "Social Media / Search Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - {
          label: "Excerpt for Articles List",
          name: "listSummary",
          widget: "string",
          required: false,
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          buttons: ["bold", "italic", "link", "bulleted-list", "numbered-list"],
        }
      
