backend:
  name: github
  repo: EvictionLab/eviction-lab-website
  branch: cms-dev
media_folder: "static/uploads" # Folder where user uploaded files should go
publish_mode: editorial_workflow
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
- name: "weekly-reports" # Used in routes, e.g., /admin/collections/blog
  identifier_field: "h1"
  label: "Weekly Reports" # Used in the UI
  folder: "/content/weekly-reports" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  editor:
    preview: false
  preview_path: weekly-reports/{{slug}}
  fields: # The fields for each document, usually in front matter
    - {label: "City Name", name: "h1", widget: "string"}
    - {label: "Created Date", name: "date", widget: "datetime"}
    - {label: "Body", name: "body", widget: "markdown", buttons: ["bold", "italic", "link", "bulleted-list", "numbered-list"]}
