backend:
  name: github
  repo: EvictionLab/eviction-lab-website
  branch: cms-dev

# FOR LOCAL DEVELOPMENT:
# ---
# - uncomment the backend below
# - run `npx netlify-cms-proxy-server` to serve content

# backend:
#   name: git-gateway
# local_backend: true

media_folder: "static/uploads" # Folder where user uploaded files should go
publish_mode: editorial_workflow
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    preview_path: /weekly-reports/{{slug}}
    files:
      - label: "Weekly Reports"
        name: "weekly-reports"
        file: "content/weekly-reports/_index.md"
        fields:
          - {
              label: "Draft",
              name: "draft",
              widget: "boolean",
              hint: "When draft is on, the page will not be published to the live site",
            }
          - label: "Meta"
            name: "cascade"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Browser Window Title",
                  name: title,
                  widget: string,
                  hint: "Title for the browser window or tab",
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "string",
                  hint: "Not visible, but used for search engine optimization",
                }
              - {
                  label: "Social Description",
                  name: "socialDescription",
                  widget: "string",
                  hint: "Description for the thumbnail when page is shared on social media",
                }
              - {
                  label: "Facebook Share Image",
                  name: "fbImage",
                  widget: "image",
                  hint: "Image used when page is shared on Facebook",
                }
              - {
                  label: "Twitter Share Image",
                  name: "twImage",
                  widget: "image",
                  hint: "Image used when page is shared on Twitter",
                }
          - { label: Heading, name: h1, widget: string }
          - {
              label: "Updated Date",
              name: "date",
              widget: "date",
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Funded By"
            name: "fundedby"
            widget: "object"
            fields:
              - {
                  label: Heading,
                  name: heading,
                  widget: string,
                  default: "",
                }
              - label: "Links"
                name: "links"
                widget: "list"
                summary: "{{fields.alt}}"
                fields:
                  - {
                      label: "URL",
                      name: "url",
                      widget: "string",
                      hint: "e.g. https://website.com/",
                    }
                  - {
                      label: "Logo",
                      name: "logo",
                      widget: "image",
                    }
                  - {
                      label: "Alternate Text",
                      name: "alt",
                      widget: "string",
                    }
      - label: "Weekly Reports (Methods)"
        name: "weekly-reports/methods"
        file: "content/weekly-reports/methods.md"
        fields:
          - {
              label: "Draft",
              name: "draft",
              widget: "boolean",
              hint: "When draft is on, the page will not be published to the live site",
            }
          - label: "Meta"
            name: "cascade"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Browser Window Title",
                  name: title,
                  widget: string,
                  hint: "Title for the browser window or tab",
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "string",
                  hint: "Not visible, but used for search engine optimization",
                }
              - {
                  label: "Social Description",
                  name: "socialDescription",
                  widget: "string",
                  hint: "Description for the thumbnail when page is shared on social media",
                }
              - {
                  label: "Facebook Share Image",
                  name: "fbImage",
                  widget: "image",
                  hint: "Image used when page is shared on Facebook",
                }
              - {
                  label: "Twitter Share Image",
                  name: "twImage",
                  widget: "image",
                  hint: "Image used when page is shared on Twitter",
                }
          - {
              label: Page Name,
              name: h1,
              widget: string,
              hint: "used in the breadcrumb",
            }
          - {
              label: "Updated Date",
              name: "date",
              widget: "date",
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Weekly Reports (Similar Resources)"
        name: "weekly-reports/similar-resources"
        file: "content/weekly-reports/similar-resources.md"
        fields:
          - {
              label: "Draft",
              name: "draft",
              widget: "boolean",
              hint: "When draft is on, the page will not be published to the live site",
            }
          - label: "Meta"
            name: "cascade"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Browser Window Title",
                  name: title,
                  widget: string,
                  hint: "Title for the browser window or tab",
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "string",
                  hint: "Not visible, but used for search engine optimization",
                }
              - {
                  label: "Social Description",
                  name: "socialDescription",
                  widget: "string",
                  hint: "Description for the thumbnail when page is shared on social media",
                }
              - {
                  label: "Facebook Share Image",
                  name: "fbImage",
                  widget: "image",
                  hint: "Image used when page is shared on Facebook",
                }
              - {
                  label: "Twitter Share Image",
                  name: "twImage",
                  widget: "image",
                  hint: "Image used when page is shared on Twitter",
                }
          - {
              label: Page Name,
              name: h1,
              widget: string,
              hint: "used in the breadcrumb",
            }
          - {
              label: "Updated Date",
              name: "date",
              widget: "date",
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Weekly Reports (Acknowledgements)"
        name: "acknowledgements"
        identifier_field: name
        file: "content/weekly-reports/acknowledgements.md"
        fields:
          - {
              label: "Draft",
              name: "draft",
              widget: "boolean",
              hint: "When draft is on, the page will not be published to the live site",
            }
          - label: "Meta"
            name: "cascade"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Browser Window Title",
                  name: title,
                  widget: string,
                  hint: "Title for the browser window or tab",
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "string",
                  hint: "Not visible, but used for search engine optimization",
                }
              - {
                  label: "Social Description",
                  name: "socialDescription",
                  widget: "string",
                  hint: "Description for the thumbnail when page is shared on social media",
                }
              - {
                  label: "Facebook Share Image",
                  name: "fbImage",
                  widget: "image",
                  hint: "Image used when page is shared on Facebook",
                }
              - {
                  label: "Twitter Share Image",
                  name: "twImage",
                  widget: "image",
                  hint: "Image used when page is shared on Twitter",
                }
          - {
              label: Page Name,
              name: h1,
              widget: string,
              hint: "used in the breadcrumb",
            }
          - {
              label: "Updated Date",
              name: "date",
              widget: "date",
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Weekly Reports (Get the Data)"
        name: "data"
        identifier_field: name
        file: "content/weekly-reports/get-the-data.md"
        fields:
          - {
              label: "Draft",
              name: "draft",
              widget: "boolean",
              hint: "When draft is on, the page will not be published to the live site",
            }
          - label: "Meta"
            name: "cascade"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Browser Window Title",
                  name: title,
                  widget: string,
                  hint: "Title for the browser window or tab",
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "string",
                  hint: "Not visible, but used for search engine optimization",
                }
              - {
                  label: "Social Description",
                  name: "socialDescription",
                  widget: "string",
                  hint: "Description for the thumbnail when page is shared on social media",
                }
              - {
                  label: "Facebook Share Image",
                  name: "fbImage",
                  widget: "image",
                  hint: "Image used when page is shared on Facebook",
                }
              - {
                  label: "Twitter Share Image",
                  name: "twImage",
                  widget: "image",
                  hint: "Image used when page is shared on Twitter",
                }
          - {
              label: Page Name,
              name: h1,
              widget: string,
              hint: "used in the breadcrumb",
            }
          - {
              label: "Updated Date",
              name: "date",
              widget: "date",
            }
          - {label: "Introduction", name: intro, widget: markdown}  
          - label: "Table Column Headers"
            name: "headers"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Header 1",
                  name: "siteheader",
                  widget: "string",
                }
              - {
                  label: "Header 2",
                  name: "baselineheader",
                  widget: "string",
                }
              - {
                  label: "Header 3",
                  name: "geoheader",
                  widget: "string",
                }
              - {
                  label: "Header 4",
                  name: "fileheader",
                  widget: "string",
                }
          - label: Data Table Rows
            name: data
            widget: list
            fields:
              - {label: Site, name: site, widget: string}
              - {label: Baseline Years, name: years, widget: string}
              - {label: Smallest Geography, name: geo, widget: string}
              - {label: Data File, name: file, widget: file}   
          - { label: "Body (below table)", name: "body", widget: "markdown" }    
  - name: "weekly-reports"
    identifier_field: "h1"
    label: "Weekly Reports"
    folder: "/content/weekly-reports"
    extension: md
    create: true
    slug: "{{fields.slug}}"
    filter: { field: "collection", value: true } # only show collection items
    editor:
      preview: false
    preview_path: weekly-reports/{{slug}}
    fields: # The fields for each document, usually in front matter
      - {
          label: "Collection",
          name: "collection",
          widget: "hidden",
          default: true,
        }
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          hint: "When draft is on, the page will not be published to the live site",
          default: true,
        }
      - {
          label: "Browser Title",
          name: "title",
          widget: "string",
          hint: "Browser window title",
        }
      - { label: "City Name", name: "h1", widget: "string" }
      - {
          label: "Slug (URL)",
          name: "slug",
          widget: "string",
          hint: "Should match city name and 2 letter state code (e.g. el-paso-tx)",
        }
      - { label: "Updated Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
