name: Triggered Deploy to AWS

on:
  push:
    branches:
      - staging
      - production
      - ets-last-update-action

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Set bucket for branch
        id: deploy-bucket
        run: |
          if [[ $GITHUB_REF == 'refs/heads/production' ]]; then
              echo "::set-output name=S3_BUCKET::eviction-lab-website"
              echo "::set-output name=CLOUDFRONT_ID::${{ secrets.AWS_CLOUDFRONT_ID_PROD }}"
          elif [[ $GITHUB_REF == 'refs/heads/production' ]]; then
              echo "::set-output name=S3_BUCKET::eviction-lab-website-staging"
              echo "::set-output name=CLOUDFRONT_ID::${{ secrets.AWS_CLOUDFRONT_ID_STAGING }}"
          fi

      - run: cp themes/evictionlab/layouts/robots.prod.txt themes/evictionlab/layouts/robots.txt
        if: github.ref == 'refs/heads/production'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.84.0"
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - name: Update ETS Date
        run: |
          python scripts/update-ets-date.py
          git config user.email "coreytegeler@gmail.com"
          git config user.name "coreytegeler"
          git add .
          git commit -m "Chore(ETS): Auto-increment date"
          git fetch origin ets-last-update-action
          git push origin HEAD:ets-last-update-action

      - run: hugo

      - name: Deploy
        uses: InscribeAI/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ steps.deploy-bucket.outputs.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          SOURCE_DIR: "public"
          AWS_CF_DISTRIBUTION_ID: ${{ steps.deploy-bucket.outputs.CLOUDFRONT_ID }}
