name: Scheduled Deploy to Production
on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
jobs:
  productionPromotion:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: production

      - name: Reset promotion branch
        run: |
          git fetch origin staging:staging
          git reset --hard staging
          git push --force origin production

      - run: cp themes/evictionlab/layouts/robots.prod.txt themes/evictionlab/layouts/robots.txt

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.101.0"
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: hugo

      - name: Deploy
        uses: InscribeAI/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: "eviction-lab-website"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          SOURCE_DIR: "public"
          AWS_CF_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_ID_PROD }}
