name: Rebuild Landing Page (production)
# data from this repo is also fetched by the landing page (https://github.com/hyperobjekt/eviction-lab)
# when data updates, hit netlify build hook to rebuild corresponding deploy 
# (https://app.netlify.com/sites/eviction-lab-site/configuration/deploys#build-hooks)

on:
  push:
    branches:
      - production
  # scheduled deploy doesn't trigger a "push" event, so we need to listen for it explicitly
  workflow_run:
    workflows: ["Scheduled Deploy to Production"]
    types:
      - completed

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy
        run: |
          curl -X POST -d {} https://api.netlify.com/build_hooks/653193b94ea3932842de3b72
          echo "Deploy production branch. Details:"
          echo "ref: $GITHUB_REF, commit: $GITHUB_SHA, event: $GITHUB_EVENT_NAME, actor: $GITHUB_ACTOR"