name: Rebuild Landing Page (development)
# data from this repo is also fetched by the landing page (https://github.com/hyperobjekt/eviction-lab)
# when data updates, hit netlify build hook to rebuild corresponding deploy 
# (https://app.netlify.com/sites/eviction-lab-site/configuration/deploys#build-hooks)

on:
  push:
    branches:
      - development

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy
        run: |
          curl -X POST -d {} https://api.netlify.com/build_hooks/653193a24ea393286fde3c2e
          echo "Deploy development branch. Details:"
          echo "ref: $GITUHB_REF, commit: $GITHUB_SHA, event: $GITHUB_EVENT_NAME, actor: $GITHUB_ACTOR"